### ISSUE TITLE
Not starting 

### ISSUE THREAD

**Issue by tuxflo** [aptalca/docker-digikam#4]
Hey! I just found your digikam docker and wanted to try it (not having docker experience so far) but after executing the command as described:

```
docker run -d --name="DigiKam" -e EDGE="0" -e HEIGHT="720" -e WIDTH="1280" -v /path/to/config:/tmp:rw -v /path/to/pictures:/home/flo/Pictures -v /etc/localtime:/etc/localtime:ro -p 5555:8080 aptalca/docker-digikam
```

nothing happens. If I try to start digikam manually it shows me:

```
docker run aptalca/docker-digikam digikam
libdc1394 error: Failed to initialize libdc1394
digikam: cannot connect to X server
```

I'm running Arch Linux (manjaro) 64bit if that matters.
Thanks for helping,
Flo

**Comment by aptalca** [comment]
Hi Flo,

The mount points in your run command are wrong.

You should be modifying the left side of the mount point, not the right side. The right side is internal to the container and they should be static. The left side is what is being exposed to the container.

For instance if you want the config files to reside at /tmp on your server, then use "/tmp:/config:rw"
and if you want to map your pictures folder, use "/home/flo/Pictures:/Pictures:rw" and within digikam, you will be able to access your photos through /Pictures

Let me know if that solves the issue

**Comment by tuxflo** [comment]
Hey thanks for the reply!
I changed the mount settings, but I'm still getting the errors mentioned above. I think the first one is OpenCV related as described [here](http://stackoverflow.com/questions/12689304/ctypes-error-libdc1394-error-failed-to-initialize-libdc1394).
But I think the main issue is that it can not connect to an Xserver.

**Comment by aptalca** [comment]
`docker run aptalca/docker-digikam digikam` is not supposed to work. Once the container runs, it uses the mount points and other info for processing before it launches digikam in openbox and serves through xvnc (it doesn't just execute digikam). Without the other environment variables and attempting direct execution, it is likely to crash.

Can you elaborate on "nothing happens"? Run `docker ps` to see if the container is running?

Also please post the new run command you are using so I can make sure all variables are correct.

If the container is running, just go to http://SERVERIP:PORT/#/client/c/digiKam in a browser to access the interface
